### ISSUE TITLE
For check_jobs* calls, some timestamps are in microseconds not milliseconds

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#103]
For example:

```
           "updated": 1568051547380,
            "running": 1568051258898000,
            "finished": 1568051547346000,
           "created": 1568051224000
```

Note the differences. The correct times are updated and created, which correspond to 2019-09-09T17:52:27.380Z and 2019-09-09T17:47:04.000Z respectively. The times for running and finished are 1000x what they should be, as if the second -> millisecond conversion is being applied twice.
For completeness, the dates reported for running and finished are +051659-07-26T10:08:18.000Z and +051659-07-29T18:15:46.000Z. (Using Javascript's toISOString() method, as in `new Date(1568051547346000).toISOString();`.

**Comment by bio-boris** [comment]
@eapearson Which job ID is this?

**Comment by Tianhao-Gu** [comment]
is it a recent job? Old job might have this behavior but should be fixed by  https://github.com/kbase/execution_engine2/pull/95

**Comment by bio-boris** [comment]
5d7683efaa5a4d298c5dc977

**Comment by eapearson** [comment]
Sorry, I forgot to post up the job id. Yeah, it was 5d769018aa5a4d298c5dc97a But I see it is fixed now, so awesome!
As a reminder, are timestamps now stored in the db as millisecond epoch and essentially copied in to the result, or are they stored in native MongoDB format and transformed?
Nevermind, it looks like one of the supported date formats is indeed millisecond epoch (as is second.subsecond,).

**Comment by bio-boris** [comment]
@eapearson They are stored as epoch seconds with a millisecond timestamp. time.time() basically. The apis return them multiplied by * 1000

**Comment by bio-boris** [comment]
This was fixed by https://github.com/kbase/execution_engine2/pull/101/files

Can we close this @eapearson

**Comment by Tianhao-Gu** [comment]
closing issue. It should be fixed by now. @eapearson of course, let us know if you still see this issue happening.
