### ISSUE TITLE
get_job_logs should take offset and limit

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#108]
Current the get_job_logs method takes the parameter "skip_lines" as the only control over the log entries returned.

We also need a limit on the number of entries returned, in order to support paging. This is commonly named "limit".

In fact, I'd recommend adding the more standard parameter "offset" along with its partner "limit", to support paging (using the parameter names used in other ee2 methods and other services.)

For compatibility, skip_lines could be retained. Not sure how to handle both being supplied, but probably an error would be best, rather than some precedence or mixing of them (e.g. limit and skip_lines)

For "offset" and "limit" I don't think we should allow limit to be omitted, because it is unclear whether the service would impose a default (e.g. 1000) is or whether the behavior would be "unlimited" as it is now. 

A user of the api can use offset with a high limit to achieve fetching all log entries, yet still retain some control and safety.

**Comment by bio-boris** [comment]
> For "offset" and "limit" I don't think we should allow limit to be omitted, because it is unclear whether the service would impose a default (e.g. 1000) is or whether the behavior would be "unlimited" as it is now.


@eapearson The limit is 2000 right now
https://github.com/kbase/execution_engine2/blob/develop/lib/execution_engine2/SDKMethodRunner.py#L993-L995

**Comment by eapearson** [comment]
@bio-boris on my side I'm requiring that the offset and limit always be specified, so I don't plan on using the default value. I do of course see the value of having a default value for casual usage, but on the ui side I anticipate that accessing logs will always be paged (even if the display side appears to be scrolling), and that requires always specifying the offset and limit.
