### ISSUE TITLE
is_admin - should it really take the token as a parameter?

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#109]
I'm not a snob about these things, since the token is passed as clear text in the header anyway. And I can see the utility of is_admin taking a token parameter when used in some other context, but I wonder about allowing it to be used in jsonrpc like this, since it gives the token additional exposure, and arguably the jsonrpc body is more accessible than the header (although this is not nearly the same issue as embedding a token in a url).

Its usage implies it is used to inquire about the admin status of some other user by their token. I'm not sure why a token would be sent rather than a username, unless there is a specific use case of a secure admin interface which deals with other user's tokens.

And exposing other user's tokens like this is probably not a good idea.

I can simply not send the token as a parameter and avoid the issue, but others may fall prey to it.

It is also arguably confusing because it provides two forms of the same api call; on the surface a naïve user of the api may just see the token as a parameter and use it, not realizing that the same token is already being sent in the header.

There must be a use case this supports?

If so, and it is admin-related, perhaps it could be isolated in an admin-only version of is_admin, e.g. admin_is_admin?

**Comment by bio-boris** [comment]
Let's change the token to username

**Comment by eapearson** [comment]
That is good, and much shorter!

**Comment by eapearson** [comment]
I mean, it is still a _bit_ confusing. I remember an api method similar to this which took an optional username, and there was confusion about the dual nature of it (using the username associated with the token if no username passed, otherwise using that username). Mistakes were made, but quickly fixed.
The spec documentation does cover this though.

**Comment by bio-boris** [comment]
I think that 
1) no username passed = check for yourself
2) username passed = check other user

Like so
https://github.com/kbase/catalog/blob/master/catalog.spec#L788

https://github.com/kbase/catalog/blob/70df64ce481af183c15f24b7fdbe3b3869f03e32/lib/biokbase/catalog/Impl.py#L1339-L1355

Or if you only want to check on yourself, then you don't pass in anything

**Comment by Tianhao-Gu** [comment]
@eapearson @bio-boris in order to check other user's roles without providing a token, the requester must be an auth admin. Do you still want me to switch token to the user name? 

@eapearson does the user who runs the job page need to check other user's admin rights? Is it efficient to check oneself's admin rights for the job page? If you just call is_admin without any params, it checks admin rights for whoever calls it.

**Comment by Tianhao-Gu** [comment]
@eapearson Looks like we could close this for now? If in the future we do need to check other people's admin rights, we could revisit this.

**Comment by bio-boris** [comment]
@Tianhao-Gu To close this we must
* Update the spec file to request nothing
* Remove the token from the function/ function signature

**Comment by Tianhao-Gu** [comment]
@bio-boris `user_token` is optional. Do we really need to remove it?

**Comment by bio-boris** [comment]
I think that is what we agreed in the standup today.

**Comment by bio-boris** [comment]
@eapearson Should this be renamed to am_admin instead?

**Comment by eapearson** [comment]
@bio-boris interesting question! You know I look good names. I think `am_admin` might be confusing because it is so unusual. A very explicit name could be "is_the_current_user_an_admin".
But seriously, I think "is_admin" is both fine. The same method name is used in some other apps. Most of them seem to take the username as the sole argument, and I would bet they default to the username attached to the token if the username is omitted.
Also, `is_` is a good prefix for a predicate function, just as in some contexts (camelCase) just `p`, or `?` or `p` as suffixes.

**Comment by Tianhao-Gu** [comment]
is_admin requires no params and checks the current user's admin rights. closing issue. @eapearson feel free to let us know if you still see any problems with this.
