### ISSUE TITLE
Permissions for running jobs in shared narratives

### ISSUE THREAD

**Issue by bio-boris** [kbase/execution_engine2#117]
* Download Jobs are Condor Run_jobs

All run_jobs require

```
        ws_auth = self.get_workspace_auth()
        if not ws_auth.can_write(params["wsid"]):
            logging.debug(
                f"User {self.user_id} doesn't have permission to run jobs in workspace {params['wsid']}."
            )
            raise PermissionError(
                f"User {self.user_id} doesn't have permission to run jobs in workspace {params['wsid']}."
            )
```

So if they don't have write permissions, they can't run download jobs from public or r/o 
shared narratives unless they make a copy of the narrative?

**Comment by bio-boris** [comment]
@briehl

**Comment by bio-boris** [comment]
@briehl Could you please give feedback

**Comment by bio-boris** [comment]
@Tianhao-Gu This is related to the 
```
Export as:FASTQSTAGINGJSONCancel
Error: Couldn’t submit condor job: java.lang.IllegalStateException: Error running condorCommand: condor_submit -terse -spool /mnt/awe/condor/submit/logs/tgu2/5df2978c88aa5c1e3ef4dc46/5df2978c88aa5c1e3ef4dc46.sub , ERROR: Can’t find address of local schedd
```
Error you found. So when it calls the run_job here, we should before create a workspace for the download job to fit inside of for that user.

**Comment by bio-boris** [comment]
Looks like the client needs to be updated at https://github.com/kbase/narrative/blob/py3-update/kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js#L177-L202

**Comment by bio-boris** [comment]
see https://github.com/kbase/execution_engine2/pull/165

**Comment by Tianhao-Gu** [comment]
@bio-boris @briehl Fixed 

> Looks like the client needs to be updated at https://github.com/kbase/narrative/blob/py3-update/kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js#L177-L202

**Comment by bio-boris** [comment]
@Tianhao-Gu do you have a link to the code where the jobs are submitted from the narrative call? I wonder if we are matching everything from there. I think the download panel might be missing `string app_id;`

**Comment by Tianhao-Gu** [comment]
@bio-boris Yea. The PR added `app_id`. 
https://github.com/kbase/narrative/pull/1566

**Comment by bio-boris** [comment]
@Tianhao-Gu awesome. Do you mind sharing a link where the narrative submits jobs to ee2 for normal jobs?

**Comment by Tianhao-Gu** [comment]
@bio-boris 
for normal job:
https://github.com/kbase/narrative/blob/py3-update/src/biokbase/narrative/jobs/appmanager.py#L340

for batch job:
https://github.com/kbase/narrative/blob/py3-update/src/biokbase/narrative/jobs/appmanager.py#L153

**Comment by bio-boris** [comment]
@Tianhao-Gu Thanks! I didn't even know there was a batch app, I thought that it was KBParallels

**Comment by bio-boris** [comment]
We ended up removing this requirement
