### ISSUE TITLE
Expose the client group job run on?

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#126]
In the job browser, each job shows the client group(s) assigned to the job.
Well, it doesn't really do that. It shows he client group(s) the app is configured for, but does not actually show the current client group being utilized once the job is running.
The app client group is provided by the Catalog.
Can ee2 return the actual client group the job has been assigned to?
This would be an improvement, so is a feature request, but I think the current implementation is ambiguous since it doesn't explain this difference and implies that they are one and the same. (Although it seems that most job client group constraints are just a single client group.)

**Comment by bio-boris** [comment]
This is now available in JobInput.requirements.clientgroup

```
class JobRequirements(EmbeddedDocument):
    """
    To be populated by ee2 during init of a job record
    """

    clientgroup = StringField()
    cpu = IntField()
    memory = IntField()
    disk = IntField()
    estimate = EmbeddedDocumentField(Estimate)
```

**Comment by bio-boris** [comment]
@eapearson Can we close this ticket

**Comment by eapearson** [comment]
I'll check this out and close after implementing on my end.

**Comment by eapearson** [comment]
Confirmed on my end (finally).
