### ISSUE TITLE
all job logs have the same timestamp

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#134]
In fact, the job log timestamp is always `1574115014695`, which is Monday, November 18, 2019 22:10:14.695 (utc).

Two examples shown below:

params:
```
{
  "version": "1.1",
  "id": "123",
  "method": "execution_engine2.get_job_logs",
  "params": [
    {
      "job_id": "5dd4e26aa0cc453db4bb0f0c"
    }
  ]
}
```

Result:
```
{
    "version": "1.1",
    "result": [
        {
            "lines": [
                {
                    "line": "Job runner recieved Callback URL http://10.42.214.9:43759/",
                    "linepos": 1,
                    "error": false,
                    "ts": 1574115014695
                },
                {
                    "line": "Running on ci-core-condorworker-mixed-privileged-partionable-1 (10.42.214.9) in /cdr/ci/dir_14987/JobRunner",
                    "linepos": 2,
                    "error": false,
                    "ts": 1574115014695
                },
                {
                    "line": "Client group: njs",
                    "linepos": 3,
                    "error": false,
                    "ts": 1574115014695
                },
                {
                    "line": "Job already run or canceled",
                    "linepos": 4,
                    "error": false,
                    "ts": 1574115014695
                }
            ],
            "last_line_number": 4
        }
    ],
    "id": "123"
}
```

params:

```
{
  "version": "1.1",
  "id": "123",
  "method": "execution_engine2.get_job_logs",
  "params": [
    {
      "job_id": "5dd540027ec5a1da6ebb0f09"
    }
  ]
}
```

result:

```
{
    "version": "1.1",
    "result": [
        {
            "lines": [
                {
                    "line": "Job runner recieved Callback URL http://10.42.214.9:33893/",
                    "linepos": 1,
                    "error": false,
                    "ts": 1574115014695
                },
                {
                    "line": "Running on ci-core-condorworker-mixed-privileged-partionable-1 (10.42.214.9) in /cdr/ci/dir_15956/JobRunner",
                    "linepos": 2,
                    "error": false,
                    "ts": 1574115014695
                },
                {
                    "line": "Client group: njs",
                    "linepos": 3,
                    "error": false,
                    "ts": 1574115014695
                },
                {
                    "line": "Job already run or canceled",
                    "linepos": 4,
                    "error": false,
                    "ts": 1574115014695
                }
            ],
            "last_line_number": 4
        }
    ],
    "id": "123"
}
```

**Comment by Tianhao-Gu** [comment]
@eapearson Thanks. This issue should be fixed. Old job logs will still be impacted. But new job logs will be fixed.

**Comment by eapearson** [comment]
@Tianhao-Gu Do you mean old jobs as in pre-ee2? Or old jobs as in anything run before the latest release?
I assume the latter, because 5dce023179edf472eecdf4c2 from 11/15/19 or so has the problem.
I started a new job a few minutes ago in order to have a look at the logs, but after 15 minutes it is still queued: 5dd5bb2e84c2ba8aa657eaaf
I'll check the job later and add another comment here.

**Comment by Tianhao-Gu** [comment]
@eapearson old jobs as anything run before the fix.

**Comment by eapearson** [comment]
@Tianhao-Gu Do you mean old jobs as in pre-ee2? Or old jobs as in anything run before the latest release?
I assume the latter, because 5dce023179edf472eecdf4c2 from 11/15/19 or so has the problem.
I started a new job a few minutes ago in order to have a look at the logs, but after 30 minutes it is still queued: 5dd5bb2e84c2ba8aa657eaaf
I'll check the job later and add another comment here.

**Comment by eapearson** [comment]
BTW I think we should just omit the `ts` field for old job logs, since providing an incorrect time is not useful. What would be useful is having a way of displaying old job logs (no timestamp) and new ones (with timestamp).
Perhaps this could be achieved with a version field. Of course I could utilize the ol' hack of inspecting the first array element to determine the structure, and switching to the non-timestamp renderer. This can't be done on a row basis because the logs are presented in a table, so a column needs to be set aside for the timestamp.

**Comment by Tianhao-Gu** [comment]
@bio-boris Any suggestions? We could remove auto-saving for ts in job logs. However, future logs won't have ts fields.

**Comment by Tianhao-Gu** [comment]
according to transfer script, seems like old logs never have `ts` field?
https://github.com/kbase/execution_engine2/blob/develop/lib/execution_engine2/db/models/transfer/transfer_logs.py#L89-L95

**Comment by Tianhao-Gu** [comment]
one option I am thinking is moving default for `ts` while transferring. After that, we add back default `ts`.

**Comment by bio-boris** [comment]
Sure, we aren't calling the API so we can insert them however we want into the db using the script. It just goes off of the given model. (Or  maybe we can insert an empty value or a -1)

**Comment by Tianhao-Gu** [comment]
set default tz to 0 in transfer script:
https://github.com/kbase/execution_engine2/pull/207

**Comment by Tianhao-Gu** [comment]
I think this ticket can be closed once we completely transferred all old logs.

**Comment by bio-boris** [comment]
@eapearson @Tianhao-Gu 
Transfer is complete, all records now a 0 in the database. 
The api now returns nothing if the TS is not available. See https://github.com/kbase/execution_engine2/pull/209/files

**Comment by eapearson** [comment]
Perfect, this is fixed and fine now.
