### ISSUE TITLE
job entries: Subjobs and out of range values

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#138]
I'm now seeing (maybe they were present before, but I never ran across them), past job entries with very incomplete structure and out of range values. E.g. below are two entries from 2016:

```json
 {
                    "_id": "57eeef56e4b0b05cf8996c02",
                    "user": "eaptest30",
                    "authstrat": "DEFAULT",
                    "wsid": -1,
                    "status": "error",
                    "updated": 1475276646979,
                    "running": 1475276640790,
                    "finished": 1475276646966,
                    "errormsg": "/kb/module/bin/../lib/genome_transform/genome_transformServer.pm terminating\n",
                    "msg": "/kb/module/bin/../lib/genome_transform/genome_transformServer.pm terminating\n Execution engine job for genome_transform.genbank_to_genome",
                    "error_code": 0,
                    "scheduler_type": "awe",
                    "job_input": {
                        "wsid": -1,
                        "method": "genome_transform.genbank_to_genome",
                        "requested_release": "dev",
                        "params": [
                            {
                                "workspace": "eaptest30:1475276576555",
                                "contigset_id": "ath_hy5_demo2_contigset",
                                "genbank_file_path": "/data/bulktest/eaptest30//ath_hy5_demo2.fq copy",
                                "genome_id": "ath_hy5_demo2.fq-copy"
                            }
                        ],
                        "service_ver": "dde33725d2aa5f333169caccdabcfa8a227a7e53",
                        "app_id": "genome_transform.genbank_to_genome",
                        "source_ws_objects": [],
                        "narrative_cell_info": {}
                    },
                    "job_output": {
                        "error": {
                            "message": "/kb/module/bin/../lib/genome_transform/genome_transformServer.pm terminating\n",
                            "error": "/kb/module/bin/../lib/genome_transform/genome_transformServer.pm terminating\n",
                            "name": "JSONRPCError",
                            "code": -32603
                        },
                        "version": "1.1"
                    },
                    "job_id": "57eeef56e4b0b05cf8996c02",
                    "created": 1475276630000
                },
                {
                    "_id": "57eeef57e4b0b05cf8996c03",
                    "user": "eaptest30",
                    "authstrat": "DEFAULT",
                    "wsid": -1,
                    "status": "error",
                    "updated": 1475276631994,
                    "running": 0,
                    "finished": 0,
                    "msg": "ws.11739.obj.1 57eeef56e4b0b05cf8996c02",
                    "error_code": 0,
                    "scheduler_type": "awe",
                    "job_id": "57eeef57e4b0b05cf8996c03",
                    "created": 1475276631000
                },
```

The out of range value is present in both job records, which have a `wsid` of -1. The second entry has running and finished times of 0, which is technically valid, but certainly out of the valid range of times for jobs. For both cases, I can work around by detecting these values and treating them as if they were missing or null, but it would be better if they were simply omitted.

The difference in structure is that the second  entry has no job input or output. Now, in the job browser at present we don't use the job output, but we do use the job input to determine the app id and wsid (although now I noticed wsid appears in both the job input and on the top level job structure, so I can just use the latter).

This looks like a subjob -- the message is a reference to the job above. The issue of subjobs has come up in at least one bug report, because they present as incomplete job browser entries (as provided by kb_metrics).

Are we sure we want to include subjobs in the job log? (perhaps widen to include opinions from @psdehal and @scanon) If so, we should talk about how to represent them and explain them to the user.

**Comment by bio-boris** [comment]
Do we care about jobs with a wsid of -1? check_jobs_for_wsid will never normally return them.
They would only be returned for check_jobs_for_user. Maybe the simple fix is to have a checkbox that says "include subjobs", otherwise by default request a filter of "wsid != -1"

 I think its OK if they are broken. We will have a record that they ran at some point, but no user will ever see them. 
As for jobs with a WSID, there are 785 that do not have a job input object. 400 of those are mine.
Here are some remants
https://gist.github.com/bio-boris/b5b134c82aa776a1d0c362f85aced4de
All of these jobs do not exist in NJS at all, which leads me to believe that these jobs don't matter.

However I will go and update the script to not put in the fields rather than put in a 0, as requested

**Comment by eapearson** [comment]
So if we are going to support subjobs, let me ask whether we can support a more positive way of indicating that they are subjobs (other than wsid of -1). E.g. a boolean field named "is_subjob". And in addition a field which contains the parent job id (other than overloading the "msg" field).

I mean, the information is there, in the msg field. If wsid=-1 ALWAYS means subjob, and subjobs ALWAYS have a msg field formatted like "<object_ref> <parent_job_id>" then we can use  this as the official structure for a subjob. 

On the other hand, the other job cited also has wsid=-1 but is not a subjob.

Remember too that check_jobs_for_user is the basis for the user facing job browser, and check_jobs_for_all, nearly identical, for admins. Admins surely do want to be able to see subjobs, and I agree that users probably don't need to see them.

That is why I included @scanon and @psdehal here so they could provide input.

**Comment by bio-boris** [comment]
@eapearson ee2 will not be creating records for subjobs

**Comment by eapearson** [comment]
Just spoke to Paramvir -- he wants subjobs both for users and admins.

For users he wants them to appear as a separate tab in the job inspector popup, but not in the main  listing (table), and for the admin view they should appear in the table as well.

So does this mean that ee2 does not include any support for subjobs -- they just exist for old jobs?

**Comment by bio-boris** [comment]
Yes, ee2 does not include any support for subjobs.

**Comment by scanon** [comment]
I would like to clarify this next week. 

Shane

**Comment by bio-boris** [comment]
@eapearson 
We decided that ee2 will not create records for subjobs, but there may be a feature request for adding logs for subjobs into a different structure or place.?

I created this issue for testing out BATCH jobs, which ee2 will still support
https://github.com/kbase/execution_engine2/issues/142

**Comment by eapearson** [comment]
@scanon @psdehal can we clarify whether we should support old subjobs? Perhaps just don't import them into ee2? 

The ee2 spec states, `Sub jobs will add  this id to the NJS database under the field "parent_job_id"`. Does that mean that subjects will be "converted" to batch jobs in ee2 or this is only relevant to NJS (which is where the NJS database lives? Unless this means the NJS legacy database for ee2)?

Are batch jobs structured like as regular jobs, but just have the parent_job_id field populated (in the run job params)? Can someone point me to an app which generates batch jobs?

**Comment by bio-boris** [comment]
@eapearson  Changed the spec description so that should clear it up for you hopefully. let me know if it doesnt.
```
            parent_job_id - EE2 id of the parent of a batch job. Batch jobs will add
            this id to the EE2 database under the field "parent_job_id"
```
Yes, batch jobs are structured like regular jobs except with parent_job_id
All apps generate batch jobs, you just have to press the batch jobs button.

**Comment by bio-boris** [comment]
@eapearson I think the ticket name is wrong, since it appears you are referring to Batch jobs and not sdk subjobs.

**Comment by eapearson** [comment]
Cool @bio-boris thanks for the clarification.

**Comment by eapearson** [comment]
I say let's close this ticket, since it has wandered, ee2 has changed much since it was created, and it involves several concerns.
If any of these concerns remain, separate tickets will be created.
