### ISSUE TITLE
backward compatibility tests

### ISSUE THREAD

**Issue by Tianhao-Gu** [kbase/execution_engine2#151]
- [x] DB rollback script
- [ ] set up local narrative backward compatibility testing

**Comment by Tianhao-Gu** [comment]
rollback DB instruction added:
https://github.com/kbase/execution_engine2/blob/develop/lib/execution_engine2/db/models/transfer/README.md#rollback-from-ee2-to-njsujs

**Comment by bio-boris** [comment]
@Tianhao-Gu Can we close this?
