### ISSUE TITLE
Projection should include and not exclude and default projection should be none? Or should we rename to `exclude_fields` ?

### ISSUE THREAD

**Issue by bio-boris** [kbase/execution_engine2#170]
https://github.com/kbase/execution_engine2/blob/develop/lib/execution_engine2/execution_engine2Impl.py#L510

https://github.com/kbase/execution_engine2/blob/develop/lib/execution_engine2/execution_engine2Impl.py#L626

@Tianhao-Gu If we change this  from
` projection=params.get("projection", ["job_output"]),`
to
` projection=params.get("projection",),`

Do we have to update narrative?

**Comment by Tianhao-Gu** [comment]
@bio-boris No. Narrative does `ee2.check_jobs({'job_ids': job_ids, 'projection': [], 'return_list': 0})`

**Comment by Tianhao-Gu** [comment]
rename `projection` to `exclude_fields`
https://github.com/kbase/execution_engine2/pull/171

I will update narrative codes once the above PR is merged in. But changes won't break the narrative.

**Comment by bio-boris** [comment]
Awesome

**Comment by bio-boris** [comment]
Done as per #171
