### ISSUE TITLE
Make sure previous completed jobs display correctly and Show Logs Correctly

### ISSUE THREAD

**Issue by bio-boris** [kbase/execution_engine2#180]
![image](https://user-images.githubusercontent.com/1258634/73094446-3a30ee80-3ea6-11ea-9a9b-e2b6973fac0d.png)

**Comment by bio-boris** [comment]
![image](https://user-images.githubusercontent.com/1258634/73094482-474ddd80-3ea6-11ea-8ff4-9f2be2c743cf.png)

**Comment by briehl** [comment]
This should be complete and up on CI.

**Comment by bio-boris** [comment]
@briehl Woohoo! I opened up the cells, they showed that nasty timestamp, and then suddenly it got updated to the correct version! Thanks!

**Comment by briehl** [comment]
Great! That's how it works - it'll look weird, then request an update, and be fixed. Once the narrative's saved, that'll stay fixed next time, since the state'll be cached in the cell.
