### ISSUE TITLE
Some jobs cannot be cancelled

### ISSUE THREAD

**Issue by bio-boris** [kbase/execution_engine2#181]
![image](https://user-images.githubusercontent.com/1258634/73097452-ce9e4f80-3eac-11ea-9100-4d409d06eaf7.png)

**Comment by bio-boris** [comment]
I think this is resolved.. I don't remember how to recreate this though

**Comment by briehl** [comment]
I think it was resolved with the last update. Let's close for now, but we can re-open if needed.
