### ISSUE TITLE
Cancel other user's jobs

### ISSUE THREAD

**Issue by bio-boris** [kbase/execution_engine2#203]
Cancel other user's jobs in a shared narrative causes a narrative error. Job is cancelled correctly, but narrative cell is messed up

**Comment by briehl** [comment]
It's likely messed up in the original user's narrative, too, at least it is in my tests.
At first it looks canceled, but on save/reload, it shows an error.

Querying the EE2 service gives this state for the job (a little truncated):
job id 5e8661ac15a2d7adc0ffaaeb on CI:

```
{'user': 'wjriehl',
 'status': 'error',
 'updated': 1585865163094,
 'queued': 1585865132924,
 'finished': 1585865163094,
 'errormsg': 'Unexpected Job Error',
 'terminated_code': 0,
 'error_code': 2,
 'job_id': '5e8661ac15a2d7adc0ffaaeb',
 'created': 1585865132000}
```

I would have expected `status: terminated` with `terminated_code: 0`. It showing up with `status: error` is what puts the cell in an error state.

**Comment by bio-boris** [comment]
@briehl I think maybe I fixed that today. The cancel job wasn't going through so the job ran, and when it ran, it saw that it was cancelled, so it finished with an error.. I removed that and now the job fails quietly. So we should test it again today.

**Comment by briehl** [comment]
Is that up on CI? I can test when it's ready.

**Comment by bio-boris** [comment]
@briehl yes

**Comment by briehl** [comment]
That fixed it - there's still an incorrect error reported in different parts of the cell, though. I'm working through them.

**Comment by briehl** [comment]
I think this particular case is fixed with the EE2 update. There are others related to shared narratives I'll open issues for and get to work on.
