### ISSUE TITLE
Job enters error state with log if canceled while queued

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#211]
I canceled a job, 5e8737e17c5f51cc084d35f0, a RAST annotation, a few seconds after it was queued. During the time it was queued, no logs are expected, so the Narrative does not show job log. Immediately after cancelation, the Narrative also does not show the job log, because nothing is expected until after the job starts running.

The job state also indicates both that it was queued AND that it resulted in an error. I can certainly see how a queued job could throw an error (well, not the job, which in reality doesn't exist yet, but the job running machinery could encounter an error and terminate the job in an error state).

However, this would be unexpected for the user, and the error message itself, ""Unexpected Job Error", indicates that it is unexpected for the job runner as well.

The narrative does not handle the situation well, as shows the the job was canceled (even though the job status is "error"), perhaps because there is both a `terminated_code, and it detects cancelation by the presence of the terminated code.

However, the job state also contains an error_code of 2, and an errormsg.

The job log indicates the job runner started running the canceled job, but then encountered an internal error, or at least an unexpected error, which itself triggered an error in the job runner.

However, refreshing the job status tab, say by clicking on another tab and then back to it, shows a job log, as well as does a direct call to the `get_job_logs` method.

There are at least a couple of issues here:

1. the production of a job log for a job canceled during queue phase is new behavior, so tools do not expect this. That is why the narrative shows no jobs initially, and does show jobs later. (That is actually a bug in the old job log viewer in the narrative -- it should not even attempt to fetch jobs if a job has not yet been run.)

2. The job log shows an error. This should not be the case for a canceled job, because it contradicts the job state, and reveals that job cancelation is not being handled correctly.

3. The job state has contradictory information, both a termination and an error code and message.

4. The job state and log are contradictory - the job state does not indicate a run start time, yet the job log indicates that the job runner started (attempting to) run the job.

I reproduced this with another app (prokka, job id 5e8736bf60f28a7f8910b94e), with identical behavior. BTW I was attempting to produce a job with no log entries in order to set up a test for that scenario.

The expected behavior, at least from the user, is that the cancellation of a queued job would simply remove it from the queue. If, internally, the job engine cannot detect job cancelation until it is taken from the queue, it should detect this before actually attempting to run it. And  if that is not possible, that it should handle the behavior thrown when the job runner detects that it has been canceled.

There should not be a log for queued jobs, since they have nothing to report, and that should not change when they are canceled while queued. Perhaps if the condition is detected, and a log has been created, it can be removed. But if not, we'll need to consider how we can handle this. Essentially job cancelation will need to be a two phase process. Initial job cancelation state would not be a terminal state, it would be more akin to "canceling", as in, job cancelation is in progress. During "canceling" state, the job state would continue to be monitored, and a job log would be expected as well. A final state of "canceled" would be akin to job cancelation state now, with the exception that if the job was queued while canceled (no run start time), there will (or may) be a log.

Below are some results for the prokka job:

```json
{
    "version": "1.1",
    "result": [
        {
            "lines": [
                {
                    "line": "Job runner recieved Callback URL http://10.42.51.135:46317/",
                    "linepos": 1,
                    "is_error": 0,
                    "ts": 1585919993279
                },
                {
                    "line": "Running job 5e8737e17c5f51cc084d35f0 on ci-core-condorworker-mixed-privileged-partionable-3-1 (10.42.51.135) in /cdr/ci3/dir_8351/JobRunner",
                    "linepos": 2,
                    "is_error": 0,
                    "ts": 1585919993699
                },
                {
                    "line": "Client group: njs",
                    "linepos": 3,
                    "is_error": 0,
                    "ts": 1585919994419
                },
                {
                    "line": "Job already run or canceled",
                    "linepos": 4,
                    "is_error": 1,
                    "ts": 1585919995487
                },
                {
                    "line": "An unhandled exception resulted in a premature exit of the app. Job id is 5e8737e17c5f51cc084d35f0",
                    "linepos": 5,
                    "is_error": 1,
                    "ts": 1585919997346
                }
            ],
            "last_line_number": 5,
            "count": 5
        }
    ],
    "id": "123"
}
```

The job was never started, according to the job state returned by `check_job`:

```json
{
    "version": "1.1",
    "result": [
        {
            "user": "kbaseuitest",
            "authstrat": "kbaseworkspace",
            "wsid": 47458,
            "status": "error",
            "updated": 1585919996308,
            "queued": 1585919970536,
            "finished": 1585919996308,
            "errormsg": "Unexpected Job Error",
            "terminated_code": 0,
            "error_code": 2,
            "scheduler_type": "condor",
            "scheduler_id": "14465",
            "job_input": {
                "wsid": 47458,
                "method": "RAST_SDK.annotate_genome",
                "params": [
                    {
                        "input_genome": "47458/6/1",
                        "call_features_rRNA_SEED": 0,
                        "call_features_tRNA_trnascan": 0,
                        "call_selenoproteins": 0,
                        "call_pyrrolysoproteins": 0,
                        "call_features_repeat_region_SEED": 0,
                        "call_features_strep_suis_repeat": 0,
                        "call_features_strep_pneumo_repeat": 0,
                        "call_features_crispr": 0,
                        "call_features_CDS_glimmer3": 0,
                        "call_features_CDS_prodigal": 0,
                        "annotate_proteins_kmer_v2": 1,
                        "kmer_v1_parameters": 1,
                        "annotate_proteins_similarity": 1,
                        "resolve_overlapping_features": 0,
                        "call_features_prophage_phispy": 0,
                        "retain_old_anno_for_hypotheticals": 0,
                        "output_genome": "rast_output_1",
                        "workspace": "kbaseuitest:narrative_1581717956468"
                    }
                ],
                "service_ver": "0.1.1",
                "app_id": "RAST_SDK/reannotate_microbial_genome",
                "source_ws_objects": [
                    "47458/6/1"
                ],
                "parent_job_id": "None",
                "requirements": {
                    "clientgroup": "njs",
                    "cpu": 4,
                    "memory": 23000,
                    "disk": 100
                },
                "narrative_cell_info": {
                    "run_id": "49f1420f-391b-4a5a-9b4c-ef0b9982a337",
                    "token_id": "85035cfd-7900-4b55-b011-dba311236705",
                    "tag": "release",
                    "cell_id": "4ed3c54e-c58c-460e-a5be-b1e255f5146e"
                }
            },
            "job_id": "5e8737e17c5f51cc084d35f0",
            "created": 1585919969000
        }
    ],
    "id": "123"
}
```

**Comment by bio-boris** [comment]
This is resolved

https://github.com/kbase/JobRunner/pull/20
