### ISSUE TITLE
don't log tokens

### ISSUE THREAD

**Issue by MrCreosote** [kbase/execution_engine2#326]
https://github.com/kbase/execution_engine2/blob/eba99eee965a2c27af71b92f247a76d596abbdea/lib/execution_engine2/sdk/EE2Runjob.py#L217

`params` contains the token.

**Comment by MrCreosote** [comment]
https://github.com/kbase/execution_engine2/blob/develop/lib/execution_engine2/utils/Condor.py#L350-L353

`submit` contains the token

**Comment by MrCreosote** [comment]
https://github.com/kbase/execution_engine2/blob/eba99eee965a2c27af71b92f247a76d596abbdea/lib/execution_engine2/sdk/EE2Runjob.py#L251

`submission_info` contains the token

**Comment by bio-boris** [comment]
These are fixed somewhere in https://github.com/kbase/execution_engine2/pull/277 and https://github.com/kbase/execution_engine2/pull/289
