### ISSUE TITLE
Auth wsid on createJob

### ISSUE THREAD

**Issue by bio-boris** [kbase/execution_engine2#61]
Users can currently pass in arbitrary WSID's. Check for permissions to the WSID before you allow a job to be run in that WS..

Also maybe pass in an arbitrary job nickname or category or something like that so a user can identify a job..

**Comment by briehl** [comment]
I think this solves that (top of `SDKMethodRunner.run_job`: 
https://github.com/kbase/execution_engine2/blob/develop/lib/execution_engine2/SDKMethodRunner.py#L359-L362
