### ISSUE TITLE
Create a narrative with 2000+ jobs and see if loading performance is improved

### ISSUE THREAD

**Issue by bio-boris** [kbase/execution_engine2#62]
Create a narrative with 2000+ jobs and see if loading performance is improved

**Comment by Tianhao-Gu** [comment]
test load narrative:
https://ci.kbase.us/narrative/ws.44898.obj.1

**Comment by Tianhao-Gu** [comment]
created 2000+ jobs in 44898. 

`check_workspace_jobs` run on average 4.69" and `check_jobs` run on average 2.6" for 20 executions.

<img width="1014" alt="Screen Shot 2019-12-02 at 1 35 16 PM" src="https://user-images.githubusercontent.com/3953823/69991212-e68ccf00-150c-11ea-85f7-b4b7edb391f5.png">
<img width="1008" alt="Screen Shot 2019-12-02 at 1 35 26 PM" src="https://user-images.githubusercontent.com/3953823/69991216-e8ef2900-150c-11ea-8945-c54b04104a79.png">

**Comment by bio-boris** [comment]
@Tianhao-Gu thanks!
We should compare it against PROD and see how it long it takes there to load 2000 narratives on a page load... Not sure how to do this though..

**Comment by Tianhao-Gu** [comment]
Created 2000 jobs in appdev. 
https://appdev.kbase.us/narrative/ws.34516.obj.1

It takes over a minute to grab 2000 jobs in appdev. Looks like a good boost in performance. 

<img width="1014" alt="Screen Shot 2019-12-03 at 11 31 58 AM" src="https://user-images.githubusercontent.com/3953823/70074729-ea7a2900-15c0-11ea-9db6-fcc0ca3fdfd1.png">

**Comment by bio-boris** [comment]
Thanks!
