### ISSUE TITLE
Job errors are strings, not structures

### ISSUE THREAD

**Issue by briehl** [kbase/execution_engine2#68]
When a job ends with an error, `check_job` returns a stringified structure that can't be parsed by the usual json tools. It should be returned as a structure with keys: "name", "code", "message", and "error", as in the `JsonRpcError` object in the spec: https://github.com/kbase/execution_engine2/blob/develop/execution_engine2.spec#L205

**Comment by Tianhao-Gu** [comment]
I think EE2 is now fixed. `finished_job` is accepting error as a structure. 

Waiting on JobRunner PR fix merge:
https://github.com/kbase/JobRunner/pull/15

**Comment by briehl** [comment]
Great! Thanks!
