### ISSUE TITLE
Timestamp format inconsistent and not compliant with the spec

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#69]
ee2 job state timestamp fields should be consistent with the definition in the spec file, but are not. Some include sub second time, most don't have the tz offset, none have the "T" separator between date and time, and probably the spec should reference the actual standard (ISO8601 by the look of it). 

The spec states:

```
 A time in the format YYYY-MM-DDThh:mm:ssZ, where Z is either the
        character Z (representing the UTC timezone) or the difference
        in time to UTC in the format +/-HHMM, eg:
            2012-12-17T23:24:06-0500 (EST time)
            2013-04-03T08:56:32+0000 (UTC time)
            2013-04-03T08:56:32Z (UTC time)
```

E.g.  this is snipped from the results of get_job in CI:

```
 "updated": "2019-09-09 17:52:27.380000",
 "running": "2019-09-09 17:47:38",
 "finished": "2019-09-09 17:52:27",
 "created": "2019-09-09 17:47:04+00:00"
```

**Comment by Tianhao-Gu** [comment]
@eapearson 
format record job timestamp: https://github.com/kbase/execution_engine2/pull/75

'created': '2019-10-16T21:04:40.559732+00:00'

**Comment by Tianhao-Gu** [comment]
per https://github.com/kbase/execution_engine2/pull/84. all of the time fields should be in epoch format now.

**Comment by scanon** [comment]
This is fixed.
