### ISSUE TITLE
Missing timestamp fields

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#70]
The spec provides the following timestamp fields for job state:

```
updated - string - timestamp of the last time the status was updated
running - string - timestamp of when it entered the running state
created - string - timestamp when the job was created
finished - string - timestamp when the job was finished
```

of these `finished`, `running`, and `created` are job states.

however the actual job states are:

```
created - job has been created in the service
estimating - an estimation job is running to estimate resources required for the main
		job, and which queue should be used
queued - job is queued to be run
running - job is running on a worker node
finished - job was completed successfully
error - job is no longer running, but failed with an error
terminated - job is no longer running, terminated either due to user cancellation,
	 admin cancellation, or some automated task
```
	 
given that finished, error, and terminated are all variants of a "finished" state, this leaves `queued` and `estimating` as unrepresented with state transition timestamps.

Is there a reason? Are `queued` and `estimating` collapsed into "created"? It seems to me that separate state transition timestamps would be warranted.

**Comment by bio-boris** [comment]
@eapearson
We have not yet ironed out queued vs estimating, but we can add the queued field here
#73

**Comment by scanon** [comment]
We are deferring estimated.  We will make a new issue for estimating.
