### ISSUE TITLE
Terminology and identifiers for the "finished" state and timestamp.

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#71]
It seems to me that the "finished" state identifier is ambiguous. There should be a distinction between a job finishing with success and simply being finished (stopped, either due to successful completion, halted due to error, or terminated). The usage of a "finished" state transition timestamp applies to all reasons for which a job has stopped, but the usage of "finished" as a state identifier separate from "error" and "terminated" indicates that it indicates a job having successfully run to completion.

I suggest "completed" for the state identifier for successfully completed jobs.

Since this api is new, it is a good chance to make this better from the start!

**Comment by scanon** [comment]
Fixed.
