### ISSUE TITLE
Need "is_admin" method

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#72]
In order to determine whether admin feature should be exposed to a given user, we need a technique for determining if a user is an ee2 admin. 
I'd suggest a simple method "is_admin" which returns true if the user identified by the normally provided token is considered an admin user, and false otherwise.

**Comment by bio-boris** [comment]
@eapearson  Is https://github.com/kbase/execution_engine2/blob/develop/lib/execution_engine2/SDKMethodRunner.py#L450 

Sufficient?

**Comment by bio-boris** [comment]
@briehl Do you want want to expose this as a public endpoint?

**Comment by briehl** [comment]
Sure, if that'll help.

**Comment by Tianhao-Gu** [comment]
https://github.com/kbase/execution_engine2/pull/93

**Comment by Tianhao-Gu** [comment]
@eapearson `is_admin` func is deployed
