### ISSUE TITLE
status of condor_stats_service?

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#74]
Referring to https://github.com/bio-boris/condor_stats_service, which is utilized in the catalog plugin's queue admin tool. 

I'm specifically interested in the methods `queue_status` and `job_status`, which are the only methods used in the catalog plugin

The current prod ui release uses v1.3.2 of the catalog plugin, 
https://github.com/kbase/kbase-ui-plugin-catalog/blob/9bc3a60c80b41b776c573e8b9ada3be62deaa4dd/src/plugin/iframe_root/modules/widgets/kbaseCatalogQueue.js#L643
https://github.com/kbase/kbase-ui-plugin-catalog/blob/9bc3a60c80b41b776c573e8b9ada3be62deaa4dd/src/plugin/iframe_root/modules/widgets/kbaseCatalogQueue.js#L678

`job_status` is similar to the `check_job...` family of methods, but is only intended for admin usage. That would seem similar to the intention of `check_jobs_date_range_for_all`.

(The current version of the catalog client, v2.0.3, is nearly identical in this respect - that module was not changed significantly.)

**Comment by bio-boris** [comment]
@eapearson Can we close this one?

**Comment by eapearson** [comment]
The impetus for this issue, and it looks like I didn't state it explicitly, was whether functionality provided by https://github.com/bio-boris/condor_stats_service could be folded into ee2.
I was also worried that this might more of a developer/diagnostics service, and not in the main stream of kbase core services.
Let's close this for now, and when it comes time to add more queue "smarts" into the job browser or other user tools, address that need head-on.
