### ISSUE TITLE
check_jobs* family of methods should return list not map

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#80]
Since the check_jobs_date_range_for_* will be paged (still needs offset to implement this), the results need to be a sorted list. I believe that issue is in a separate ticket. Currently the results are a map, with the job id as the key and the job state info as the value.

https://github.com/kbase/execution_engine2/blob/8142da9bea25aa5f3acf0faf5115dce2b24af5fc/execution_engine2.spec#L321

For consistency, check_jobs_date_range_for_user and check_jobs_date_range_for_all return a list, then check_jobs perhaps should as well. In the case of check_jobs, the order should be the order in which the job_ids were provided.

**Comment by Tianhao-Gu** [comment]
@eapearson Due to narrative backward compatibility, I think we have to keep check_jobs the way it is now. Since narrative cache old job states. We can change check_jobs_date_range_for_ the same as check_jobs if you prefer.

**Comment by bio-boris** [comment]
So this ticket is 4 parts, here is what's done

- [ ]  check_jobs_date_range_for_user return a list
- [ ]  check_jobs_date_range_for_all return a list
- [ ]  check_jobs return a list
- [ ]  check_jobs return a list in order provided

**Comment by Tianhao-Gu** [comment]
@bio-boris @briehl I think check_jobs cannot return a list due to backward compatibility in narrative. Otherwise old jobs won't work in narrative due to cache?

**Comment by Tianhao-Gu** [comment]
or we can make it return as list as an option.

**Comment by bio-boris** [comment]
@eapearson 
Can you please confirm
So for jobs 100, 9000, 200, 500 
you would expect
[ {100}, {9000}, {200}, {500} ] 
And if a record was missing youd get
[ {100}, {empty}, {200}, {500} ]

**Comment by Tianhao-Gu** [comment]
closing this issue. @eapearson feel free to let me know if you still see this as an issue.
