### ISSUE TITLE
Update times to epoch seconds

### ISSUE THREAD

**Issue by bio-boris** [kbase/execution_engine2#83]
- [ ] Convert all timestamps to epoch in mongo, 
- [ ] Change api endpoints to return epoch times (or maybe an option for timestamps?)
- [ ] Change api endpoints to accept epoch times (or maybe an option for timestamps?)

@eapearson Which of these do you think is most appropriate?

**Comment by bio-boris** [comment]
So is that epoch WITH milliseconds, or epoch IN milliseconds?

**Comment by Tianhao-Gu** [comment]
@eapearson https://github.com/kbase/execution_engine2/pull/84 should address this. All of the time fields should now be in epoch format with milliseconds. e.g. `1571977116.194329`

**Comment by eapearson** [comment]
That should be epoch time *in* milliseconds, if the goal is to be aligned with the representation of epoch time in other services.

**Comment by Tianhao-Gu** [comment]
👍 https://github.com/kbase/execution_engine2/pull/86 update time fields in milliseconds
