### ISSUE TITLE
Need sorting and improved search support for check_jobs_date_range_for_user, check_jobs_date_range_for_all

### ISSUE THREAD

**Issue by eapearson** [kbase/execution_engine2#85]
Handling search and sort in the client is not going to work, just can't scale it well enough, so we need to ensure that sort and search are implemented in the ee2 methods check_jobs_date_range_for_user, check_jobs_date_range_for_all. 
Where fields are specified below, 

Sorting:
We need to sort by:  natural (insertion) order or one or more of created, updated. Support for ascending or descending order.

Search: 
Search is already implemented well for time range; Field level search is in place but may need changes.

time range:
This supports search over a time range bounded by a lower and upper timestamp. This is already implemented.

free text search:
This supports the "single search terms" style of searching, in which the user enters a set of one or more search terms without specifying a search field. 

Matching at a minimum should be case insensitive substrings, but regex would be great (it can help with more precise matches when need be).

All terms would narrow the search (AND).

Matches should be made for at least one of app (id, module, name), username, job id, possibly other fields. The api should support a list of fields which are to be searched over.

field level exact:
This supports filtering style search, in which the filter is provided as a list of field/value-list pairs which are compared exactly, "AND"ed together. In the interface, these will be selected by the user rather than entered directly, thus they can and should be exact. In some cases (e.g. job status) we need to filter by membership in a set (one or more statuses), so I think the general form would be to compare the field to a list of values ($in comparison).

The candidate fields are job_id, user, workspace id, app id, job status. Job status is the only filter currently implemented in the job browser ui, but I imagine other filters would be useful, especially for admin usage to allow narrowing down to jobs of interest.

An update to the filter support has already been requested. The current field level filtering is supported by a list of strings in "field=value" format. It would be better if this were a json formatted list of small structures, like
```
[
  {
     "field": "user",
     "in": ["mmouse", "dduck"]
  }
]
```

or 
```
{
   "user": ["mmouse", "dduck"]
}
```

I think the former offers the advantage of being extensible (e.g. comparison operators other than "in"), the latter more concise and non-extensible.

**Comment by bio-boris** [comment]
@eapearson  @Tianhao-Gu 

I have a PR at #131  for free_text search

I implemented it using mongo indexes and the mongo text_search operator.. It's pretty good, and does tokenization and stuff, however it has its downfalls, such as if a method is named
`app_name.weak_weak_weak` and you search for `weak` it won't find it, but if you search for `weak_weak_weak` it will find it

https://github.com/kbase/execution_engine2/blob/429637d712d8b3fa96e35fb1eb477a4045b86b82/test/ee2_SDKMethodRunner_test.py#L1474-L1532

There are some tradeoffs and advantages/disadvantages to doing it this way...
Maybe we would be better off to

1) Tokenize the string ourselves "apple pie,is,great" into ["apple","pie","is","great"]
2) Grab all over the mongo records, store them in memory, and then iterate over each field, and if it contains the freetext, keep it, if not, toss it away

Any suggestions would be great

**Comment by eapearson** [comment]
I think evaluation of this pros and cons should be measured against the perceived needs of free text search in the context of the job browser, so @psdehal and @scanon?

My base requirement for any search tool is that it only apply to elements that will be displayed - otherwise a user may not understand why a particular item is appearing. This can be a field which appears in the job browser table, or as in one of our search interfaces, as a snippet of text drawn from a field not normally displayed.

Another requirement is that, search needs to at a minimum match on substrings within some sensible subset of displayed fields. In other words, it should work at least as well as even basic capabilities of search interfaces for products the user is familiar with, such as an editor, browse (in page search), etc. So in the example above, failing to match on a substring of an app id is a problem.

However, it is now clear, but wasn't when I created this issue, that free text search will not reach into narrative titles, user actual names, or app titles. I'm not even sure, given these restrictions, that free text search is all that valuable. We don't have anything to search on for narrative (just wsid), app search is by app id (users are generally exposed to app titles not ids); search by username would be useful for admins. 

We also now have good field-level filtering. We can use that to create interface elements allowing a user to filter by any given field, which alleviates the need for free text search given these restrictions. E.g. the user could select to filter by a given app or narrative (choosing from from a dropdown or similar control which shows the app or narrative title), or an admin could filter by a given user. There are other ways to facilitate filter by field, e.g. selecting a value being displayed to filter by (as in jgi search.)

**Comment by bio-boris** [comment]
@eapearson We could also just use the datatables.search feature and do a javascript search..

@eapearson If we don't need this should we close this PR?

**Comment by eapearson** [comment]
Yes, still relevant. We shouldn't have classified this as an enhancement, since it is required to support search, and search is an existing feature of the job browser.

**Comment by eapearson** [comment]
Okay, we addressed this outside this thread. We've dropped free text search for now, and enhanced filtering!
